# Generated by Django 6.0.2 on 2026-02-08 11:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('atlas_call_id', models.CharField(db_index=True, help_text='Call ID from Atlas.AI platform.', max_length=255, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='outbound', max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('transcript', models.TextField(blank=True, default='')),
                ('outcome', models.CharField(choices=[('booked', 'Booked'), ('membership_inquiry', 'Membership Inquiry'), ('waitlist', 'Waitlist'), ('general', 'General Inquiry'), ('no_action', 'No Action')], default='no_action', max_length=30)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to='bookings.booking')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to='guests.guest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
