# Generated by Django 6.0.2 on 2026-03-11 07:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_checkin'),
        ('guests', '0001_initial'),
        ('spa_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('relaxation', 'Relaxation'), ('energy', 'Energy'), ('romance', 'Romance'), ('focus', 'Focus'), ('nature', 'Nature')], default='relaxation', max_length=20)),
                ('screen_video_url', models.URLField(blank=True, default='', max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('floral', 'Floral'), ('woody', 'Woody'), ('citrus', 'Citrus'), ('herbal', 'Herbal'), ('fresh', 'Fresh'), ('oriental', 'Oriental')], default='floral', max_length=20)),
                ('intensity_default', models.PositiveIntegerField(default=5)),
                ('intensity_min', models.PositiveIntegerField(default=1)),
                ('intensity_max', models.PositiveIntegerField(default=10)),
                ('icon_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SceneMusic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(blank=True, default='', max_length=200)),
                ('audio_url', models.URLField(blank=True, default='', max_length=500)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='spa_control.scene')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ActiveRoomScene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('music_enabled', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_scenes', to='bookings.booking')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_scenes', to='guests.guest')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='spa_control.scene')),
                ('current_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='spa_control.scenemusic')),
            ],
            options={
                'ordering': ['-activated_at'],
            },
        ),
        migrations.CreateModel(
            name='ActiveScent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intensity', models.PositiveIntegerField(default=5)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_scents', to='bookings.booking')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_scents', to='guests.guest')),
                ('scent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='spa_control.scentprofile')),
            ],
            options={
                'ordering': ['-activated_at'],
            },
        ),
    ]
