# Generated by Django 6.0.2 on 2026-02-08 11:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(choices=[('web_chat', 'Web Chat'), ('voice', 'Voice Call'), ('flutter', 'Flutter App'), ('admin', 'Admin')], default='web_chat', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='guests.guest')),
            ],
            options={
                'verbose_name_plural': 'Waitlist entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
