# Generated by Django 6.0.2 on 2026-02-08 11:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('max_capacity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['date', 'time_start'],
                'unique_together': {('date', 'time_start', 'time_end')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('calcom_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('calcom_booking_uid', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(choices=[('web_chat', 'Web Chat'), ('voice', 'Voice Call'), ('flutter', 'Flutter App'), ('admin', 'Admin')], default='web_chat', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='guests.guest')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.bookingslot')),
            ],
            options={
                'ordering': ['-date', '-time_start'],
            },
        ),
    ]
