# Generated by Django 6.0.1 on 2026-03-17 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_checkin'),
        ('spa_control', '0002_scene_scentprofile_scenemusic_activeroomscene_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_number',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='experience_tier',
            field=models.CharField(choices=[('full', 'Full Experience'), ('basic', 'Without Food')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='food_preference',
            field=models.CharField(blank=True, choices=[('dairy', 'Dairy'), ('meat', 'Meat')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='spa_control.scene'),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
